import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [day, setDay] = useState(2)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={`${styles.container}`}>
          <div className={`${styles.titleDiv}`}>
            <div className={styles.titleDay}>JOURS {day}</div>
          </div>
          <div className={`${styles.imgTabler}`}>
            <div className={`${styles.tabler1}`}>
              <h1 className={`${styles.text}`}>LOUPS-GAROUS</h1>
            </div>
            <div className={`${styles.tabler2}`}>
            <h1 className={`${styles.text}`}>VILLAGEOIS</h1>
            </div>
          </div>
        </div>
    </>
  );
}
